### ISSUE TITLE
Spell effects have no duration cap, resulting in them stacking for days, weeks or even month

### ISSUE THREAD

**Issue by MedievalYeetMachine** [Standing-Storm/MindOverMatter#1]
Spell effects, like "Trance State" and "Psychic Shield", have no limit on how long they can last. When the player casts them repetedly to train the skill, they can end up wit the effect stacked dozens of time and lasting for days and weeks. This is a massive problem on effects that give just straight bonuses, like "Telepathic Shield" (though its isnt exactly fun to just sit and cast the spell for an hour and then forget about it for the next few days), but with spell like "Concentration Trance" it leads to player getting a detrimental effect (x4 moves to walk is no joke) for really long period of time.
Putting a duration limit and potentially decreasing rate at which subsequent casts add duration should fix it, while still leaving player the ability to power up buffs in advance.
Alternatively, adding a spell to remove effects, either all or from a specific class, will give players the ability to end the effects early.

**Comment by Standing-Storm** [comment]
Fixed by v0.4.1
