### ISSUE TITLE
Lamps trigger json errors for some reason

### ISSUE THREAD

**Issue by MoonlightKitty26** [Standing-Storm/MindOverMatter#28]
There are weird errors that *might* be triggering a bad allocation error upon character creation. The mod files are just fine but for some reason the game still doesn't read them properly, or it might be that annoying json flexbuffer bug thing that hasn't been solved yet. I'm not a coder, so I don't know very much, but in any case I copied the error that the game itself gives and attached the debug log.
I really like the mod thus far, and I hope development continues! Thank you!

 DEBUG    : (json-error)
Json error: C:/Users/user/Desktop/cdda/dda/userdata/mods/MindOverMatter-main (2)/MindOverMatter-main/furniture_and_terrain/appliance_lighting.json:8:21: Invalid or misplaced field name "broken_symbol" in JSON data

    "item": "standing_pyrokinetic_lamp",
    "symbol": "*",
    "broken_symbol":
                    ^
                     "-",
    "categories": [ "lighting" ],
    "color": "red",

 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 333
 VERSION  : 07356b6
[debug.log](https://github.com/Standing-Storm/MindOverMatter/files/11779854/debug.log)

**Comment by Standing-Storm** [comment]
Thank you for reporting this--the game changed how they handled vehicle furniture and required an update in the pyrokinetic lamp field. It should be fixed now.
